"""Content

Revision ID: 5e054e7f3d12
Revises: 7c720c78866f
Create Date: 2025-01-10 10:04:03.423402

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e054e7f3d12"
down_revision: Union[str, None] = "7c720c78866f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=256), nullable=False),
        sa.Column("path", sa.String(length=256), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "REGULATORY_DOCUMENT",
                "DOCUMENT_FOR_MILITARY_REGISTRATION",
                "ALTERNATIVE_CIVILIAN_SERVICE_DOCUMENT",
                "CONTRACT_SERVICE_DOCUMENT",
                "GALLERY",
                name="contentcategory",
            ),
            nullable=False,
        ),
        sa.Column("is_archived", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("filename"),
        sa.UniqueConstraint("path"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contents")
    # ### end Alembic commands ###
