"""Recruitment Office Models

Revision ID: d4130308811a
Revises: 319cb5b30cc7
Create Date: 2025-01-10 16:07:32.736831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4130308811a'
down_revision: Union[str, None] = '319cb5b30cc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commissioners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('surname', sa.String(length=256), nullable=False),
    sa.Column('patronymic', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'surname', 'patronymic', name='_name_surname_patronymic_uc')
    )
    op.create_table('commissariats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('commissioner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commissioner_id'], ['commissioners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'address', name='_name_address_uc')
    )
    op.create_table('commissariat_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=256), nullable=False),
    sa.Column('type', sa.Enum('DUTY', 'MC', name='commissariatphonetype'), nullable=False),
    sa.Column('commissariat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commissariat_id'], ['commissariats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone', name='_phone_uc')
    )
    op.create_table('commissariat_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('type', sa.Enum('VK', 'INSTAGRAM', 'FACEBOOK', 'TELEGRAM', 'WHATSAPP', 'VIBER', 'TIKTOK', name='commissariaturltype'), nullable=False),
    sa.Column('commissariat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commissariat_id'], ['commissariats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', 'type', name='_url_type_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commissariat_urls')
    op.drop_table('commissariat_phones')
    op.drop_table('commissariats')
    op.drop_table('commissioners')
    # ### end Alembic commands ###
