"""Add Content Extension

Revision ID: aeb33bfd344a
Revises: 9723308a5b02
Create Date: 2025-01-23 11:24:02.074049

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aeb33bfd344a"
down_revision: Union[str, None] = "9723308a5b02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contents", sa.Column("extension", sa.String(length=7), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contents", "extension")
    # ### end Alembic commands ###
