"""init db

Revision ID: 42f6b800cb1d
Revises: 
Create Date: 2025-02-03 09:13:48.434515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42f6b800cb1d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=20), nullable=False),
        sa.Column("hashed_password", sa.String(length=512), nullable=False),
        sa.Column("full_name", sa.String(length=50), nullable=False),
        sa.Column("role", sa.Enum("ADMIN", "USER", name="role"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "contents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=256), nullable=False),
        sa.Column("path", sa.String(length=256), nullable=False),
        sa.Column("extension", sa.String(length=7), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "REGULATORY_DOCUMENT",
                "DOCUMENT_FOR_MILITARY_REGISTRATION",
                "ALTERNATIVE_CIVILIAN_SERVICE_DOCUMENT",
                "CONTRACT_SERVICE_DOCUMENT",
                "STUDENTS",
                "GALLERY",
                "PATRIOTIC_EDUCATION",
                "EVENTS",
                "MILITARY_TRAINING_CAMPS",
                "ADDRESS_AND_LINKS",
                "CONTACTS",
                name="contentcategory",
            ),
            nullable=False,
        ),
        sa.Column("is_archived", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("filename", "category", name="_filename_category_uc"),
        sa.UniqueConstraint("path"),
    )
    op.create_table(
        "tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=256), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tokens")
    op.drop_table("contents")
    op.drop_table("users")
    # ### end Alembic commands ###
