"""Initial Migrate

Revision ID: 9723308a5b02
Revises: 
Create Date: 2025-01-13 19:48:26.703130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9723308a5b02'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commissioners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('surname', sa.String(length=256), nullable=False),
    sa.Column('patronymic', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'surname', 'patronymic', name='_name_surname_patronymic_uc')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=512), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('commissariats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('commissioner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commissioner_id'], ['commissioners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'address', name='_name_address_uc')
    )
    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('REGULATORY_DOCUMENT', 'DOCUMENT_FOR_MILITARY_REGISTRATION', 'ALTERNATIVE_CIVILIAN_SERVICE_DOCUMENT', 'CONTRACT_SERVICE_DOCUMENT', 'STUDENTS', 'GALLERY', 'PATRIOTIC_EDUCATION', 'EVENTS', 'MILITARY_TRAINING_CAMPS', name='contentcategory'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename', 'category', name='_filename_category_uc'),
    sa.UniqueConstraint('path')
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('commissariat_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=256), nullable=False),
    sa.Column('type', sa.Enum('DUTY', 'MC', name='commissariatphonetype'), nullable=False),
    sa.Column('commissariat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commissariat_id'], ['commissariats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone', name='_phone_uc')
    )
    op.create_table('commissariat_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('type', sa.Enum('MAIN', 'VK', 'INSTAGRAM', 'FACEBOOK', 'TELEGRAM', 'WHATSAPP', 'VIBER', 'TIKTOK', name='commissariaturltype'), nullable=False),
    sa.Column('commissariat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commissariat_id'], ['commissariats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', 'type', name='_url_type_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commissariat_urls')
    op.drop_table('commissariat_phones')
    op.drop_table('tokens')
    op.drop_table('contents')
    op.drop_table('commissariats')
    op.drop_table('users')
    op.drop_table('commissioners')
    # ### end Alembic commands ###
