"""Update Content Unique Constraint

Revision ID: 319cb5b30cc7
Revises: 5e054e7f3d12
Create Date: 2025-01-10 11:40:01.790538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319cb5b30cc7'
down_revision: Union[str, None] = '5e054e7f3d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contents_filename_key', 'contents', type_='unique')
    op.create_unique_constraint('_filename_category_uc', 'contents', ['filename', 'category'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_filename_category_uc', 'contents', type_='unique')
    op.create_unique_constraint('contents_filename_key', 'contents', ['filename'])
    # ### end Alembic commands ###
